In [19]:
import numpy as np
import pandas as pd
from sklearn import ensemble 
from sklearn import metrics
from sklearn import model_selection

if __name__ == "__main__":
    
    df = pd.read_csv("train.csv")
    
    X = df.drop("price_range",axis=1).values
    print(X)
    y = df.price_range.values
    print(y)
    
    # define the model
    # n_jobs=-1 => use all cores
    
    classifier = ensemble.RandomForestClassifier(n_jobs=-1)
    param_grid = {
        "n_estimators":[100,200,250,300,400,500],
#          "n_estimators":[200],
        "max_depth": [1,2,5,7,11,15],
#          "max_depth": [15],
        "criterion": ["gini","entropy"]
#          "criterion": ["entropy"]
    }
    
    # initialize grid search
    # estimator is the model that we have defined
    # pram_grid is the grid of parameters
    # we use accuracy as our metric. 
    #cv = 5  means that we are using 5 fold cv (not stratified) 
    model = model_selection.GridSearchCV(
        estimator = classifier,
        param_grid= param_grid,
        scoring="accuracy",
        verbose = 10,
        n_jobs=1,
        cv=5    
    )

    # fit the model and extract best score
    model.fit(X,y)
    
    print(f"Best score : {model.best_score_}")
    
    print("Best parameters set : ")
    best_parameters = model.best_estimator_.get_params()
    
    for param_name in sorted(param_grid.keys()):
        print(f"\t{param_name}: {best_parameters[param_name]}")


[[8.420e+02 0.000e+00 2.200e+00 ... 0.000e+00 0.000e+00 1.000e+00]
 [1.021e+03 1.000e+00 5.000e-01 ... 1.000e+00 1.000e+00 0.000e+00]
 [5.630e+02 1.000e+00 5.000e-01 ... 1.000e+00 1.000e+00 0.000e+00]
 ...
 [1.911e+03 0.000e+00 9.000e-01 ... 1.000e+00 1.000e+00 0.000e+00]
 [1.512e+03 0.000e+00 9.000e-01 ... 1.000e+00 1.000e+00 1.000e+00]
 [5.100e+02 1.000e+00 2.000e+00 ... 1.000e+00 1.000e+00 1.000e+00]]
[1 2 2 ... 3 0 3]
Fitting 5 folds for each of 72 candidates, totalling 360 fits
[CV 1/5; 1/72] START criterion=gini, max_depth=1, n_estimators=100..............
[CV 1/5; 1/72] END criterion=gini, max_depth=1, n_estimators=100;, score=0.598 total time=   0.1s
[CV 2/5; 1/72] START criterion=gini, max_depth=1, n_estimators=100..............
[CV 2/5; 1/72] END criterion=gini, max_depth=1, n_estimators=100;, score=0.615 total time=   0.1s
[CV 3/5; 1/72] START criterion=gini, max_depth=1, n_estimators=100..............
[CV 3/5; 1/72] END criterion=gini, max_depth=1, n_estimators=100;, score=

[CV 5/5; 9/72] END criterion=gini, max_depth=2, n_estimators=250;, score=0.745 total time=   0.1s
[CV 1/5; 10/72] START criterion=gini, max_depth=2, n_estimators=300.............
[CV 1/5; 10/72] END criterion=gini, max_depth=2, n_estimators=300;, score=0.777 total time=   0.1s
[CV 2/5; 10/72] START criterion=gini, max_depth=2, n_estimators=300.............
[CV 2/5; 10/72] END criterion=gini, max_depth=2, n_estimators=300;, score=0.752 total time=   0.2s
[CV 3/5; 10/72] START criterion=gini, max_depth=2, n_estimators=300.............
[CV 3/5; 10/72] END criterion=gini, max_depth=2, n_estimators=300;, score=0.782 total time=   0.2s
[CV 4/5; 10/72] START criterion=gini, max_depth=2, n_estimators=300.............
[CV 4/5; 10/72] END criterion=gini, max_depth=2, n_estimators=300;, score=0.755 total time=   0.2s
[CV 5/5; 10/72] START criterion=gini, max_depth=2, n_estimators=300.............
[CV 5/5; 10/72] END criterion=gini, max_depth=2, n_estimators=300;, score=0.775 total time=   0.1s
[C

[CV 4/5; 19/72] END criterion=gini, max_depth=7, n_estimators=100;, score=0.863 total time=   0.1s
[CV 5/5; 19/72] START criterion=gini, max_depth=7, n_estimators=100.............
[CV 5/5; 19/72] END criterion=gini, max_depth=7, n_estimators=100;, score=0.845 total time=   0.1s
[CV 1/5; 20/72] START criterion=gini, max_depth=7, n_estimators=200.............
[CV 1/5; 20/72] END criterion=gini, max_depth=7, n_estimators=200;, score=0.863 total time=   0.1s
[CV 2/5; 20/72] START criterion=gini, max_depth=7, n_estimators=200.............
[CV 2/5; 20/72] END criterion=gini, max_depth=7, n_estimators=200;, score=0.882 total time=   0.1s
[CV 3/5; 20/72] START criterion=gini, max_depth=7, n_estimators=200.............
[CV 3/5; 20/72] END criterion=gini, max_depth=7, n_estimators=200;, score=0.885 total time=   0.1s
[CV 4/5; 20/72] START criterion=gini, max_depth=7, n_estimators=200.............
[CV 4/5; 20/72] END criterion=gini, max_depth=7, n_estimators=200;, score=0.850 total time=   0.1s
[

[CV 5/5; 28/72] END criterion=gini, max_depth=11, n_estimators=300;, score=0.860 total time=   0.2s
[CV 1/5; 29/72] START criterion=gini, max_depth=11, n_estimators=400............
[CV 1/5; 29/72] END criterion=gini, max_depth=11, n_estimators=400;, score=0.877 total time=   0.2s
[CV 2/5; 29/72] START criterion=gini, max_depth=11, n_estimators=400............
[CV 2/5; 29/72] END criterion=gini, max_depth=11, n_estimators=400;, score=0.885 total time=   0.2s
[CV 3/5; 29/72] START criterion=gini, max_depth=11, n_estimators=400............
[CV 3/5; 29/72] END criterion=gini, max_depth=11, n_estimators=400;, score=0.897 total time=   0.3s
[CV 4/5; 29/72] START criterion=gini, max_depth=11, n_estimators=400............
[CV 4/5; 29/72] END criterion=gini, max_depth=11, n_estimators=400;, score=0.870 total time=   0.3s
[CV 5/5; 29/72] START criterion=gini, max_depth=11, n_estimators=400............
[CV 5/5; 29/72] END criterion=gini, max_depth=11, n_estimators=400;, score=0.870 total time=   

[CV 1/5; 38/72] END criterion=entropy, max_depth=1, n_estimators=200;, score=0.573 total time=   0.1s
[CV 2/5; 38/72] START criterion=entropy, max_depth=1, n_estimators=200..........
[CV 2/5; 38/72] END criterion=entropy, max_depth=1, n_estimators=200;, score=0.540 total time=   0.1s
[CV 3/5; 38/72] START criterion=entropy, max_depth=1, n_estimators=200..........
[CV 3/5; 38/72] END criterion=entropy, max_depth=1, n_estimators=200;, score=0.535 total time=   0.1s
[CV 4/5; 38/72] START criterion=entropy, max_depth=1, n_estimators=200..........
[CV 4/5; 38/72] END criterion=entropy, max_depth=1, n_estimators=200;, score=0.560 total time=   0.1s
[CV 5/5; 38/72] START criterion=entropy, max_depth=1, n_estimators=200..........
[CV 5/5; 38/72] END criterion=entropy, max_depth=1, n_estimators=200;, score=0.547 total time=   0.1s
[CV 1/5; 39/72] START criterion=entropy, max_depth=1, n_estimators=250..........
[CV 1/5; 39/72] END criterion=entropy, max_depth=1, n_estimators=250;, score=0.568 to

[CV 1/5; 47/72] END criterion=entropy, max_depth=2, n_estimators=400;, score=0.690 total time=   0.2s
[CV 2/5; 47/72] START criterion=entropy, max_depth=2, n_estimators=400..........
[CV 2/5; 47/72] END criterion=entropy, max_depth=2, n_estimators=400;, score=0.662 total time=   0.2s
[CV 3/5; 47/72] START criterion=entropy, max_depth=2, n_estimators=400..........
[CV 3/5; 47/72] END criterion=entropy, max_depth=2, n_estimators=400;, score=0.705 total time=   0.2s
[CV 4/5; 47/72] START criterion=entropy, max_depth=2, n_estimators=400..........
[CV 4/5; 47/72] END criterion=entropy, max_depth=2, n_estimators=400;, score=0.708 total time=   0.2s
[CV 5/5; 47/72] START criterion=entropy, max_depth=2, n_estimators=400..........
[CV 5/5; 47/72] END criterion=entropy, max_depth=2, n_estimators=400;, score=0.733 total time=   0.2s
[CV 1/5; 48/72] START criterion=entropy, max_depth=2, n_estimators=500..........
[CV 1/5; 48/72] END criterion=entropy, max_depth=2, n_estimators=500;, score=0.730 to

[CV 1/5; 56/72] END criterion=entropy, max_depth=7, n_estimators=200;, score=0.865 total time=   0.1s
[CV 2/5; 56/72] START criterion=entropy, max_depth=7, n_estimators=200..........
[CV 2/5; 56/72] END criterion=entropy, max_depth=7, n_estimators=200;, score=0.860 total time=   0.1s
[CV 3/5; 56/72] START criterion=entropy, max_depth=7, n_estimators=200..........
[CV 3/5; 56/72] END criterion=entropy, max_depth=7, n_estimators=200;, score=0.892 total time=   0.1s
[CV 4/5; 56/72] START criterion=entropy, max_depth=7, n_estimators=200..........
[CV 4/5; 56/72] END criterion=entropy, max_depth=7, n_estimators=200;, score=0.858 total time=   0.1s
[CV 5/5; 56/72] START criterion=entropy, max_depth=7, n_estimators=200..........
[CV 5/5; 56/72] END criterion=entropy, max_depth=7, n_estimators=200;, score=0.855 total time=   0.1s
[CV 1/5; 57/72] START criterion=entropy, max_depth=7, n_estimators=250..........
[CV 1/5; 57/72] END criterion=entropy, max_depth=7, n_estimators=250;, score=0.865 to

[CV 1/5; 65/72] END criterion=entropy, max_depth=11, n_estimators=400;, score=0.880 total time=   0.3s
[CV 2/5; 65/72] START criterion=entropy, max_depth=11, n_estimators=400.........
[CV 2/5; 65/72] END criterion=entropy, max_depth=11, n_estimators=400;, score=0.892 total time=   0.3s
[CV 3/5; 65/72] START criterion=entropy, max_depth=11, n_estimators=400.........
[CV 3/5; 65/72] END criterion=entropy, max_depth=11, n_estimators=400;, score=0.910 total time=   0.5s
[CV 4/5; 65/72] START criterion=entropy, max_depth=11, n_estimators=400.........
[CV 4/5; 65/72] END criterion=entropy, max_depth=11, n_estimators=400;, score=0.870 total time=   0.3s
[CV 5/5; 65/72] START criterion=entropy, max_depth=11, n_estimators=400.........
[CV 5/5; 65/72] END criterion=entropy, max_depth=11, n_estimators=400;, score=0.865 total time=   0.3s
[CV 1/5; 66/72] START criterion=entropy, max_depth=11, n_estimators=500.........
[CV 1/5; 66/72] END criterion=entropy, max_depth=11, n_estimators=500;, score=0.

In [7]:
df

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]